##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
## Global setup
- hosts: all
  user: root
  tasks: 
    - include: global_setup.yml

### C-CDA Scorecard Server
- hosts: ccda-scorecard
  user: root
  vars_files: 
    - settings/ccda_scorecard.yml
  tasks: 
    - include: ccda_scorecard.yml

## Global cleanup
- hosts: all
  user: root
  tasks: 
    - include: global_cleanup.yml
