##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
## Global setup
- hosts: all
  user: root
  tasks: 
    - include: global_setup.yml

- hosts: direct-server
  user: root
  vars_files: 
    - settings/direct_server.yml
  tasks: 
    - include: direct_server.yml

## Global cleanup
- hosts: all
  user: root
  tasks: 
    - include: global_cleanup.yml
