##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
## Global setup
- hosts: all
  user: root
  tasks: 
    - include: global_setup.yml

### C-CDA Receiver Servers
- hosts: ccda-receiver
  user: root
  vars_files: 
    - settings/ccda_receiver.yml
  tasks: 
    - include: ccda_receiver.yml

### C-CDA Scorecard Server
- hosts: ccda-scorecard
  user: root
  vars_files: 
    - settings/ccda_scorecard.yml
  tasks: 
    - include: ccda_scorecard.yml

### Direct Servers
- hosts: direct-server
  user: root
  vars_files: 
    - settings/direct_server.yml
    - settings/ccda_receiver.yml
  tasks: 
    - include: direct_server.yml

## Global cleanup
- hosts: all
  user: root
  tasks: 
    - include: global_cleanup.yml
