- name: Node.js | Add the node.js PPA
  action: command add-apt-repository -y ppa:chris-lea/node.js
          creates=/etc/apt/sources.list.d/chris-lea-node_js-${ansible_lsb.codename}.list
  register: added_node_ppa

- name: Nodejs Deps | Install packages
  tags: ccda-receiver
  action: apt pkg=$item state=installed
  with_items:
    - libxml2-dev
    - python-software-properties
    - g++
    - make

- name: Node.js | Update the apt cache for the new repository
  action: apt update_cache=yes
  when_boolean: ${added_node_ppa.changed}

- name: Node.js | Install nodejs and npm
  tags: nodejs
  action: apt pkg=$item state=installed
  when_boolean: ${added_node_ppa.changed}
  with_items:
    - nodejs

- name: Mongodb | Add the Mongodb key
  action: command apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
  tags: mongodb

- name: Mongodb | Add the Mongodb repo
  tags: mongodb
  action: copy 
          src=files/etc/apt/sources.list.d/10gen.list
          dest=/etc/apt/sources.list.d/10gen.list
          owner=root group=root mode=0644
  register: added_mongo_ppa

- name: Mongodb | Install packages
  action: apt pkg=mongodb-10gen state=installed update_cache=yes
  when_boolean: ${added_mongo_ppa.changed}
  tags: mongodb
