- name: Node.js | Add the node.js PPA
  action: command add-apt-repository -y ppa:chris-lea/node.js
          creates=/etc/apt/sources.list.d/chris-lea-node_js-{{ansible_lsb.codename}}.list
  register: added_node_ppa

- name: Nodejs Deps | Install packages
  tags: ccda-receiver
  action: apt pkg=$item state=installed
  with_items:
    - libxml2-dev
    - python-software-properties
    - g++
    - make

- name: Node.js | Update the apt cache for the new repository
  action: apt update_cache=yes
  when: added_node_ppa.changed

- name: Node.js | Install nodejs and npm
  tags: nodejs
  action: apt pkg=nodejs state=installed
